import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="/adex.umd.js"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
          window.addEventListener('load', async () => {
            console.log("AdExSDK", AdExSDK);
          
              const client = new AdExSDK.AdExClient({
    publisherId: '62c51d2b-4523-40b9-a6fb-ae4dd50fbf7b',
    domain: 'medium.com',
    selector: '#fb2df6c2-dd7f-4160-8f7f-2f68c60e814d',
    debug: true,
    adSlots:{banner:'fb2df6c2-dd7f-4160-8f7f-2f68c60e814d'}
  });
 

            console.log(client);
          });

          `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
